apiVersion: v1
kind: Service
metadata:
  name: helloworld-python-service
  labels:
    app: helloworld-python
spec:
  selector:
    app: helloworld-python
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
